# Generated by Django 4.2.7 on 2025-10-20 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('size_category', models.CharField(choices=[('small', 'Small (5-25 lbs)'), ('medium', 'Medium (30-60 lbs)'), ('large', 'Large (70-100+ lbs)')], max_length=10)),
                ('life_stage', models.CharField(choices=[('puppy', 'Puppy (4-12 months)'), ('adult', 'Adult (1-8 years)'), ('senior', 'Senior (8+ years)')], max_length=10)),
                ('preference_tags', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', 'brand'],
            },
        ),
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('age_months', models.IntegerField()),
                ('life_stage', models.CharField(choices=[('puppy', 'Puppy (4-12 months)'), ('adult', 'Adult (1-8 years)'), ('senior', 'Senior (8+ years)')], max_length=10)),
                ('activity_level', models.CharField(choices=[('low', 'Low (Senior/Inactive)'), ('moderate', 'Moderate (Average)'), ('high', 'High (Very Active)')], default='moderate', max_length=10)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('special_needs', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('dry', 'Dry Food'), ('wet', 'Wet Food'), ('treat', 'Treats')], max_length=10)),
                ('calories_per_oz', models.DecimalField(decimal_places=2, max_digits=5)),
                ('package_size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('package_unit', models.CharField(default='oz', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('affiliate_link', models.URLField(max_length=500)),
                ('preferences', models.CharField(blank=True, choices=[('budget', 'Budget-Friendly'), ('premium', 'Premium'), ('grain_free', 'Grain-Free'), ('organic', 'Organic'), ('natural', 'Natural'), ('limited_ingredient', 'Limited Ingredient')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories', models.IntegerField()),
                ('dry_food_oz', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wet_food_oz', models.DecimalField(decimal_places=2, max_digits=5)),
                ('treat_calories', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.petprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='dry_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_as_dry', to='meals.product'),
        ),
        migrations.AddField(
            model_name='meal',
            name='treats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_as_treat', to='meals.product'),
        ),
        migrations.AddField(
            model_name='meal',
            name='wet_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals_as_wet', to='meals.product'),
        ),
    ]
