# Generated by Django 4.2.7 on 2025-10-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedmeal',
            name='treat_calories',
        ),
        migrations.AddField(
            model_name='meal',
            name='reference_daily_calories',
            field=models.IntegerField(default=1000, help_text='Daily calorie needs for reference dog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='reference_dry_oz',
            field=models.DecimalField(decimal_places=2, default=300, help_text='Daily dry food in ounces for reference dog', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='reference_treat_oz',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Daily treats in ounces for reference dog', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='reference_weight',
            field=models.IntegerField(default=30, help_text='Reference dog weight this meal was calculated for (e.g., 30 lbs)'),
        ),
        migrations.AddField(
            model_name='meal',
            name='reference_wet_oz',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Daily wet food in ounces for reference dog', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedmeal',
            name='treat_oz',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
            preserve_default=False,
        ),
    ]
